spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/hackthon?serverTimezone=UTC&useLegacyDatetimeCode=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:hackathon.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

server:
  port: 8000
